### PR TITLE
Weaker NETs for Levels

### PR DESCRIPTION
**Pull request by ScallyBag**

### CODE REVIEW

**Comment by amanjpro** [comment]
Thanks a lot for the networks.

I am currently working on multi-pv, once done I work on different skill levels (by limiting search depth per different skill levels)

**Comment by ScallyBag** [comment]
Hi Amanj,

They are quite weak on their own, their grades assume that Zahak v0.2.1 was graded at 1824, as per my README.md

So limiting search depth may not be required, but that’s your call 😉

If they appear too weak or play silly moves, please feel free to go with your own instead, I will not be online for a while after my Op next Thursday.

Al.

**Comment by amanjpro** [comment]
> Hi Amanj,
> 
> They are quite weak on their own, their grades assume that Zahak v0.2.1 was graded at 1824, as per my README.md
> 
> So limiting search depth may not be required, but that’s your call 😉
> 
> If they appear too weak or play silly moves, please feel free to go with your own instead, I will not be online for a while after my Op next Thursday.
> 
> Al.

All the best luck for you! I will see what I will do :)
Thanks again

**Comment by amanjpro** [comment]
Hello again,

I had to diverge from your branch in order to work on it, and incorporate it with the engine.
I added UCI option to specify Skill levels.

Here is the diverged branch: https://github.com/amanjpro/zahak/tree/Scally-NETs

I will wait for you to test it,  before merging it in

**Comment by amanjpro** [comment]
I played against Skills level 1, and it was a bad chess player (which is perfect), and level 6 was much more solid, but still not smart enough to come up with deep tactics (which is also good)

I'll give it more try too, and see where do I rank personally :)

**Comment by ScallyBag** [comment]
Thanks for testing and incorporating them into your master 👍

Al

**Comment by amanjpro** [comment]
> Thanks for testing and incorporating them into your master +1
> 
> Al

Thank you for your great work! Really appreciate it :)
I'll be getting myself a DGT board/Pi and start using Zahak on it (just like your setup)

I'll close this PR, as it is already merged in #191

**Pull request closed without merging**
