### PR TITLE
Weaker nets for different Skill Levels

### PR DESCRIPTION
**Pull request by amanjpro**
Thanks to @ScallyBag who provided the networks, this is an attempt to incorporate them into the engine

After running a tournament between different Rustic Alpha versions with the different skills that is what I got:

```
Rank Name                                   Elo    +    - games score oppo. draws 
   1 Zahak_Skill_6                         2074   13   12  2325   83%  1829   31% 
   2 Zahak_Skill_5                         2004   12   11  2328   75%  1829   34% 
   3 rustic-alpha-3.0.0-linux-64-bit-bmi2  1870   10   10  4656   62%  1712   18% 
   4 Zahak_Skill_4                         1856   11   12  2329   53%  1829   20% 
   5 rustic-alpha-2_64-bit-bmi2            1849   10   10  4659   60%  1712   17% 
   6 rustic-alpha-1_64-bit-bmi2            1768   10   10  4662   52%  1712   15% 
   7 Zahak_Skill_3                         1630   13   13  2331   26%  1829    8% 
   8 Zahak_Skill_2                         1440   17   18  2331   11%  1829    4% 
   9 Zahak_Skill_1                         1270   25   27  2333    5%  1829    1% 
```

I anchored the ratings around Rustic Alpha 3 (using BayesElo), which 3 is rated at1870

That probably means that:

Skill Level 1: 1270
Skill Level 2: 1440
Skill Level 3: 1630
Skill Level 4: 1856
Skill Level 5: 2004
Skill Level 6: 2074

STC: http://chess.grantnet.us/test/22209/

```
ELO   | 1.51 +- 4.67 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=8MB
LLR   | 2.97 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 14472 W: 4963 L: 4900 D: 4609
```

### CODE REVIEW

**Comment by ScallyBag** [comment]
Hi Amanj,

I can’t compile this Branch, I’m getting:

Al@RPi4-SSD:~/Zahak+NETs $ make -j5
go clean ./...
rm -f engine/nn.go
CC=cc CGO_ENABLED="1" go run -gcflags "-B" -ldflags "-X 'main.netPath=default.nn' -X 'main.Version=2661680924e2fa0288f4a0ec87bf1d8d33b766dd'" netgen/nn.go
# github.com/amanjpro/zahak/engine
engine/nn_current.go:6:1: undefined: DefaultInit
make: *** [Makefile:27: netgen] Error 2

———————

I have my NETs running within Picochess without using Skill Levels, here’s my ZahakNN.uci file:

Al@RPi4-SSD:/opt/picochess/engines/armv7l-NNUE $ cat ZahakNN.uci 
[DEFAULT]
Hash = 128
Threads = 1
SyzygyPath = /opt/picochess/tablebases/syzygy
SyzygyProbeDepth = 0
#EvalFile = /opt/picochess/engines/armv7l/default.nn

[Elo@1100]
EvalFile = /opt/picochess/engines/armv7l/Scally1100.nn

[Elo@1400]
EvalFile = /opt/picochess/engines/armv7l/Scally1400.nn
 
[Elo@1600]
EvalFile = /opt/picochess/engines/armv7l/Scally1600.nn

[Elo@1800]
EvalFile = /opt/picochess/engines/armv7l/Scally1800.nn

[Elo@2000]
EvalFile = /opt/picochess/engines/armv7l/Scally2000.nn

[Elo@2200]
EvalFile = /opt/picochess/engines/armv7l/Scally2200.nn

[Elo@2289]
EvalFile = /opt/picochess/engines/armv7l/Scally2289.nn
Threads = 2

[Elo@2900]
EvalFile = /opt/picochess/engines/armv7l/default.nn
Threads = 3

Al.

**Comment by ScallyBag** [comment]
I removed this part in brackets from my Makefile:

RM=del engine\nn.go (engine\nn_*.go)

I also had to change the -mavx to -marm  in  fathom/fathom.go

it now compiles and I have skill Levels working, but I prefer my previous uci setup for Picochess.

Al

**Comment by ScallyBag** [comment]
With Skill Levels: (however the User then doesn’t know the grade of the level, hence preferring my previous uci options)

id name Zahak 8.0
id author Amanj
id EvalFile 2613885418
option name Ponder type check default false
option name Hash type spin default 128 min 1 max 120000
option name OwnBook type check default false
option name Threads type spin default 1 min 1 max 4
option name EvalFile type string default <empty>
option name BookFile type string default <empty>
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 0 min 0 max 128
option name MultiPV type spin default 1 min 1 max 120
option name Skill Level type spin default 7 min 1 max 7
uciok

———-
[DEFAULT]
Hash = 128
Threads = 1
SyzygyPath = /opt/picochess/tablebases/syzygy
SyzygyProbeDepth = 0
#EvalFile = /opt/picochess/engines/armv7l/default.nn

[Level@01]
Skill Level = 1
EvalFile = /opt/picochess/engines/armv7l/Scally1100.nn

[Level@02]
Skill Level = 2
EvalFile = /opt/picochess/engines/armv7l/Scally1400.nn

[Level@03]
Skill Level = 3
EvalFile = /opt/picochess/engines/armv7l/Scally1600.nn

[Level@04]
Skill Level = 4
EvalFile = /opt/picochess/engines/armv7l/Scally1800.nn

[Level@05]
Skill Level = 5
EvalFile = /opt/picochess/engines/armv7l/Scally2000.nn

[Level@06]
Skill Level = 6
EvalFile = /opt/picochess/engines/armv7l/Scally2200.nn

[Level@07]
Skill Level = 7
EvalFile = /opt/picochess/engines/armv7l/default.nn
Threads = 3

**Comment by tissatussa** [comment]
hi, i'm just a user, not a chess engine programmer (yet) .. today i compiled your source by `git clone` and when doing the `uci` command in terminal (i'm on Xubuntu 20.04 64-bit) i get this output :
 
zahak_8 0-dev_compiled_UCI

on top i see no version number but a large string .. i conclude this must be a dev version, because it has the new MPV option which the v8.0 asset does not have .. now i see you also added Skill Level .. i did not try to compile this very newest version by git clone, so i can't confirm .. btw. you do updates very often, it's hard to stay up-to-date !! .. nevermind, i guess it's best to wait for a new release and thus a new asset, am i right ?  On this pull request page i see Skill Level 7 has "Threads 3" .. does this mean the other Levels have threads 1 ?  I always set threads to 1 because i have a simple notebook and often i also run many other processes ..

relating to all this i have another question, but maybe i should post this in a seperate Issue : what about the EvalFile ?  I guess it's embedded but CuteChess and SCID show `default.nn` .. should this file be in the same folder ?  Or can i omit it ?  Can Zahak run without a NN ?  I see no option for that, while some other engine have a concerning checkbox ..

**Comment by amanjpro** [comment]
> RM=del engine\nn.go (engine\nn_*.go)

Oh, I thought this should only kick in when under Windows (I have no Windows to test my Makefile on it)

> it now compiles and I have skill Levels working, but I prefer my previous uci setup for Picochess.

Do you mean providing Elo instead of Skills? I can provide both, no issue. The only thing is that Elo changes overtime, and it is not FIDE Elo but CCRL based Elo, which can be misleading. I am currently running a tournament against a few versions of Rustic to determine the strengths at this point.

**Comment by amanjpro** [comment]
> relating to all this i have another question, but maybe i should post this in a seperate Issue : what about the EvalFile ? I guess it's embedded but CuteChess and SCID show default.nn .. should this file be in the same folder ? Or can i omit it ? Can Zahak run without a NN ? I see no option for that, while some other engine have a concerning checkbox ..

Zahak comes with a default net, but you can also sideload optional networks if you want.

The threads for SkillsLevel 7 is 1 by default, but 7 is what Scally uses in his setup (I believe)

My master branch is my dev branch, I update it frequently because I am working on it. If you prefer less frequent updates, but solid steps then you should probably wait for releases

**Comment by tissatussa** [comment]
> Zahak comes with a default net, but you can also sideload optional networks if you want.

What do you mean by sideload ?  Does it mean i can enter another NN file in CuteChess / SCID options, to replace the built-in `default.nn` ?  Then, which NN type should that be ?  -- i read several NN types exist and you might even have your own type ..
If i understand right, Zahak can not run without a NN ?  Some engine can .. they can even do "hybrid" evaluation.
Rest is clear. thanks.

**Comment by amanjpro** [comment]
> > Zahak comes with a default net, but you can also sideload optional networks if you want.
> 
> What do you mean by sideload ? Does it mean i can enter another NN file in CuteChess / SCID options, to replace the built-in `default.nn` ? Then, which NN type should that be ? -- i read several NN types exist and you might even have your own type .. If i understand right, Zahak can not run without a NN ? Some engine can .. they can even do "hybrid" evaluation. Rest is clear. thanks.

Zahak net's, like the ones that Scally is producing for example
Zahak is NNUE only

**Comment by ScallyBag** [comment]
“Do you mean providing Elo instead of Skills? I can provide both, no issue. The only thing is that Elo changes overtime, and it is not FIDE Elo but CCRL based Elo, which can be misleading. I am currently running a tournament against a few versions of Rustic to determine the strengths at this point.”

No, I meant I can use my previous uci file, so for me I don’t need Skill Levels or UCI_Elo combined with UCI_LimitStrength, the choice is yours.

This works for me:

Al@RPi4-SSD:/opt/picochess/engines/armv7l-NNUE $ cat ZahakNN.uci
[DEFAULT]
Hash = 128
Threads = 1
SyzygyPath = /opt/picochess/tablebases/syzygy
SyzygyProbeDepth = 0
#EvalFile = /opt/picochess/engines/armv7l/default.nn

[Elo@1100]
EvalFile = /opt/picochess/engines/armv7l/Scally1100.nn

[Elo@1400]
EvalFile = /opt/picochess/engines/armv7l/Scally1400.nn

[Elo@1600]
EvalFile = /opt/picochess/engines/armv7l/Scally1600.nn

[Elo@1800]
EvalFile = /opt/picochess/engines/armv7l/Scally1800.nn

[Elo@2000]
EvalFile = /opt/picochess/engines/armv7l/Scally2000.nn

[Elo@2200]
EvalFile = /opt/picochess/engines/armv7l/Scally2200.nn

[Elo@2289]
EvalFile = /opt/picochess/engines/armv7l/Scally2289.nn
Threads = 2

[Elo@2900]
EvalFile = /opt/picochess/engines/armv7l/default.nn
Threads = 3

Al

**Comment by amanjpro** [comment]
> “Do you mean providing Elo instead of Skills? I can provide both, no issue. The only thing is that Elo changes overtime, and it is not FIDE Elo but CCRL based Elo, which can be misleading. I am currently running a tournament against a few versions of Rustic to determine the strengths at this point.”
> 
> No, I meant I can use my previous uci file, so for me I don’t need Skill Levels or UCI_Elo combined with UCI_LimitStrength, the choice is yours.
> 
> This works for me:
> 
> Al@RPi4-SSD:/opt/picochess/engines/armv7l-NNUE $ cat ZahakNN.uci [DEFAULT] Hash = 128 Threads = 1 SyzygyPath = /opt/picochess/tablebases/syzygy SyzygyProbeDepth = 0 #EvalFile = /opt/picochess/engines/armv7l/default.nn
> 
> [Elo@1100] EvalFile = /opt/picochess/engines/armv7l/Scally1100.nn
> 
> [Elo@1400] EvalFile = /opt/picochess/engines/armv7l/Scally1400.nn
> 
> [Elo@1600] EvalFile = /opt/picochess/engines/armv7l/Scally1600.nn
> 
> [Elo@1800] EvalFile = /opt/picochess/engines/armv7l/Scally1800.nn
> 
> [Elo@2000] EvalFile = /opt/picochess/engines/armv7l/Scally2000.nn
> 
> [Elo@2200] EvalFile = /opt/picochess/engines/armv7l/Scally2200.nn
> 
> [Elo@2289] EvalFile = /opt/picochess/engines/armv7l/Scally2289.nn Threads = 2
> 
> [Elo@2900] EvalFile = /opt/picochess/engines/armv7l/default.nn Threads = 3
> 
> Al

Ah I see, but I believe for a wider audience including the net in the binary, and providing it as an option can help :)

**Comment by amanjpro** [comment]
I added my tournament results, and I believe it is more or less close to what you have found

**Pull request merged**
